services:
  qwitix-api:
    container_name: qwitix-api
    image: qwitix-api
    build:
      context: .
      dockerfile: qwitix-api/Dockerfile
      args:
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_ENVIRONMENT
        - DatabaseSettings__ConnectionString
        - JwtSettings__Issuer
        - JwtSettings__Audience
        - JwtSettings__Secret
        - StripeSettings__PublishableKey
        - StripeSettings__SecretKey
        - StripeSettings__WebhookSecret
        - Authentication__Google__ClientId
        - Authentication__Google__ClientSecret
        - CorsOptions__AllowedOriginsRaw
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongodb-data: