services:
  qwitix-api:
    build:
      context: .
      dockerfile: qwitix-api/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080"
    image: qwitix-api
